spring:
  threads:
    virtual:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      auto-index-creation: true
      database: product-db
      username: root
      password: password
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce-realm
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    status-page-url-path: /swagger-ui/index.html
app:
  maintenance:
    message: "operating system - version 1.0"
management:
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  endpoints:
    web:
      exposure:
        include: "refresh, health, prometheus, info"
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}]"
server:
  port: 8083
  error:
    include-message: always
    include-stacktrace: never