spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - file:./config-data
            - file:../config-data
        git:
          uri: https://github.com/luizspolador/ecommerce-ms.git
          search-paths: config-data
          clone-on-start: true
          default-label: main
server:
  port: 8888

